# Generated by Django 5.0.1 on 2024-03-02 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appdata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CadetMeta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("login", models.CharField(max_length=255, unique=True)),
                ("note", models.TextField(default="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="intraprofile",
            name="isBookmarked",
            field=models.BooleanField(default=False),
        ),
    ]
