# Generated by Django 5.0.2 on 2024-04-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appdata", "0002_cadetmeta_intraprofile_isbookmarked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intraprofile",
            name="login",
            field=models.CharField(
                blank=True, default=None, max_length=255, null=True, unique=True
            ),
        ),
    ]
