# Generated by Django 5.0 on 2024-01-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apptasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordwebhook",
            name="name",
            field=models.CharField(unique=True),
        ),
    ]
