# Generated by Django 5.0.2 on 2024-03-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apptasks", "0002_alter_discordwebhook_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordwebhook",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
